#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

for file in docker-compose*.test.yml; do

    echo "TODO Starting Test in ${file}..."

    # Test container run
    docker-compose --no-ansi -f "${file}" up -d && sleep 60
    docker-compose --no-ansi -f "${file}" logs -f "sut"
    docker-compose --no-ansi -f "${file}" ps
    docker-compose --no-ansi -f "${file}" logs --no-color "penpot-db"
    docker-compose --no-ansi -f "${file}" ps "penpot-db" | grep "Up"
    docker-compose --no-ansi -f "${file}" logs --no-color "penpot-backend"
    docker-compose --no-ansi -f "${file}" ps "penpot-backend" | grep "Up"
    docker-compose --no-ansi -f "${file}" logs --no-color "penpot-frontend"
    docker-compose --no-ansi -f "${file}" ps "penpot-frontend" | grep "Up"
    #docker-compose --no-ansi -f "${file}" ps "sut" | grep "Exit 0" || exit 1
    docker-compose --no-ansi -f "${file}" down

    # Test container restart
    docker-compose --no-ansi -f "${file}" up -d && sleep 60
    docker-compose --no-ansi -f "${file}" logs -f "sut"
    docker-compose --no-ansi -f "${file}" ps
    docker-compose --no-ansi -f "${file}" logs --no-color "penpot-db"
    docker-compose --no-ansi -f "${file}" ps "penpot-db" | grep "Up"
    docker-compose --no-ansi -f "${file}" logs --no-color "penpot-backend"
    docker-compose --no-ansi -f "${file}" ps "penpot-backend" | grep "Up"
    docker-compose --no-ansi -f "${file}" logs --no-color "penpot-frontend"
    docker-compose --no-ansi -f "${file}" ps "penpot-frontend" | grep "Up"
    #docker-compose --no-ansi -f "${file}" ps "sut" | grep "Exit 0" || exit 1
    docker-compose --no-ansi -f "${file}" down -v

done
