os: linux
dist: trusty

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"

script:
  - cd "$dir"
  # Test container build
  - docker-compose build
  - docker images
  # Test container run
  - travis_retry docker-compose up -d && sleep 300
  - docker-compose ps
  - docker-compose logs "uxbox_db"
  - docker-compose ps "uxbox_db" | grep "Up"
  - docker-compose logs "uxbox_backend"
  - docker-compose ps "uxbox_backend" | grep "Up"
  - docker-compose logs "uxbox_frontend"
  #- docker-compose ps "uxbox_frontend" | grep "Up"
  # Test container restart
  - docker-compose down
  - travis_retry docker-compose up -d && sleep 300
  - docker-compose ps
  - docker-compose logs "uxbox_db"
  - docker-compose ps "uxbox_db" | grep "Up"
  - docker-compose logs "uxbox_backend"
  - docker-compose ps "uxbox_backend" | grep "Up"
  - docker-compose logs "uxbox_frontend"
  #- docker-compose ps "uxbox_frontend" | grep "Up"

notifications:
  email: false

env: # Environments
    - VERSION=develop VARIANT=13-jdk-alpine
    - VERSION=develop VARIANT=11-jdk-slim
    - VERSION=develop VARIANT=11-jdk
    - VERSION=develop VARIANT=8-jre-alpine
    - VERSION=develop VARIANT=8-jre-slim
    - VERSION=develop VARIANT=8-jre
    - VERSION=master VARIANT=13-jdk-alpine
    - VERSION=master VARIANT=11-jdk-slim
    - VERSION=master VARIANT=11-jdk
    - VERSION=master VARIANT=8-jre-alpine
    - VERSION=master VARIANT=8-jre-slim
    - VERSION=master VARIANT=8-jre
