os: linux
dist: trusty

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"

script:
  - cd "$dir"
  # Test container build
  - docker-compose build
  - docker images
  # Test container run
  - travis_retry travis_wait 60 docker-compose up -d
  - docker-compose logs -f "sut"
  - docker-compose ps
  - docker-compose logs "penpot_db"
  - docker-compose ps "penpot_db" | grep "Up"
  - docker-compose logs "penpot_backend"
  - docker-compose ps "penpot_backend" | grep "Up"
  - docker-compose logs "penpot_frontend"
  #- docker-compose ps "penpot_frontend" | grep "Up"
  - docker-compose ps "sut" | grep "Exit 0"
  # Test container restart
  - docker-compose down
  - travis_retry travis_wait 60 docker-compose up -d
  - docker-compose logs -f "sut"
  - docker-compose ps
  - docker-compose logs "penpot_db"
  - docker-compose ps "penpot_db" | grep "Up"
  - docker-compose logs "penpot_backend"
  - docker-compose ps "penpot_backend" | grep "Up"
  - docker-compose logs "penpot_frontend"
  #- docker-compose ps "penpot_frontend" | grep "Up"
  - docker-compose ps "sut" | grep "Exit 0"

notifications:
  email: false

env: # Environments
    - VERSION=develop VARIANT=openjdk-15-tools-deps-alpine
    - VERSION=develop VARIANT=openjdk-15-tools-deps-buster
    - VERSION=develop VARIANT=openjdk-15-tools-deps-slim-buster
    - VERSION=develop VARIANT=openjdk-14-tools-deps-alpine
    - VERSION=develop VARIANT=openjdk-14-tools-deps-buster
    - VERSION=develop VARIANT=openjdk-14-tools-deps-slim-buster
    - VERSION=develop VARIANT=openjdk-11-tools-deps-buster
    - VERSION=develop VARIANT=openjdk-11-tools-deps-slim-buster
    - VERSION=master VARIANT=openjdk-15-tools-deps-alpine
    - VERSION=master VARIANT=openjdk-15-tools-deps-buster
    - VERSION=master VARIANT=openjdk-15-tools-deps-slim-buster
    - VERSION=master VARIANT=openjdk-14-tools-deps-alpine
    - VERSION=master VARIANT=openjdk-14-tools-deps-buster
    - VERSION=master VARIANT=openjdk-14-tools-deps-slim-buster
    - VERSION=master VARIANT=openjdk-11-tools-deps-buster
    - VERSION=master VARIANT=openjdk-11-tools-deps-slim-buster
