
name: Docker Image CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [master, develop]
        variant: [openjdk-15-tools-deps-alpine, openjdk-15-tools-deps-buster,
                  openjdk-15-tools-deps-slim-buster, openjdk-14-tools-deps-alpine,
                  openjdk-14-tools-deps-buster, openjdk-14-tools-deps-slim-buster,
                  openjdk-11-tools-deps-buster, openjdk-11-tools-deps-slim-buster]

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Build the stack
        id: docker_build
        run: docker-compose -f docker-compose.test.yml --project-directory ./images/${{ matrix.version}}/${{ matrix.variant }} build

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
