
name: Docker Image CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [master, develop]
        variant: [openjdk-15-tools-deps-alpine, openjdk-15-tools-deps-buster,
                  openjdk-15-tools-deps-slim-buster, openjdk-14-tools-deps-alpine,
                  openjdk-14-tools-deps-buster, openjdk-14-tools-deps-slim-buster,
                  openjdk-11-tools-deps-buster, openjdk-11-tools-deps-slim-buster]

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./images/${{ matrix.version}}/${{ matrix.variant }}
          file: ./images/${{ matrix.version}}/${{ matrix.variant }}/Dockerfile
          push: true
          tags: monogramm/docker-penpot-backend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
